// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Accounts, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Accounts, error)
	CreateEntrie(ctx context.Context, arg CreateEntrieParams) (Entries, error)
	CreateTransfers(ctx context.Context, arg CreateTransfersParams) (Transfers, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteEntrie(ctx context.Context, id int64) error
	DeleteTransfers(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Accounts, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Accounts, error)
	GetEntrie(ctx context.Context, id int64) (Entries, error)
	GetListAccount(ctx context.Context, arg GetListAccountParams) ([]Accounts, error)
	GetListEntrie(ctx context.Context, arg GetListEntrieParams) ([]Entries, error)
	GetListTransfers(ctx context.Context, arg GetListTransfersParams) ([]Transfers, error)
	GetTransfers(ctx context.Context, id int64) (Transfers, error)
	GetUser(ctx context.Context, username string) (Users, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Accounts, error)
	UpdateEntrie(ctx context.Context, arg UpdateEntrieParams) (Entries, error)
	UpdateTransfers(ctx context.Context, arg UpdateTransfersParams) (Transfers, error)
}

var _ Querier = (*Queries)(nil)
