apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::626635403238:user/xicoi1033
      username: xicoi1033
      groups:
        - system:masters
  mapRoles: |
    []
  mapAccounts: |
    []